import Header from '@/components/header'
import './globals.css'
import Head from './head'
import Providers from './providers'

export const metadata = {
  title: 'Carbyde - Car buying guide',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <Providers>
          <Header />
          {/* Navbar */}
          {/* Search Box */}
          <Head />
          {children}
        </Providers>

      </body>
    </html>

  )
}
